<table width="100%" border="0" cellpadding="0" cellspacing="0">
    <tbody><tr><td height="11" style="font-size: 1px; line-height: 1px;"></td></tr>

    <tr>
        <td>
            <table align="left">
                <tr>
                    <td style="font-size: 13px; font-family: Verdana, sans-serif; line-height: 18px; font-weight: 800; color: #606060">Hello, <?= $this->fullName ?> </td>
                </tr>
            </table>
        </td>
    </tr>

    <tr><td height="10" style="font-size: 1px; line-height: 1px;"></td></tr>

    <tr><td style="font-size: 13px; font-family: Verdana, sans-serif; line-height: 18px; font-weight: 500 ; color: #606060;">Use the code below to activate your account.</td></tr>

    <tr><td height="28" style="font-size: 1px; line-height: 1px;"></td></tr>

    <tr><td style="font-size: 13px; font-family: Verdana, sans-serif; line-height: 18px; font-weight: 500 ; color: #606060;"> Activation code : <?= $this->code ?></td></tr>

    <tr><td height="28" style="font-size: 1px; line-height: 1px;"></td></tr>

    <tr><td height="22" style="font-size: 1px; line-height: 1px;"></td></tr>

    <tr><td style="font-size: 13px; font-family: Verdana, sans-serif; line-height: 18px; font-weight: 800; color: #606060">Tradelist team</td>
    </tr>

    <tr><td height="26" style="font-size: 1px; line-height: 1px;"></td></tr>
    </tbody></table>