<table width="100%" border="0" cellpadding="0" cellspacing="0">
    <tbody>
    <tr>
        <td height="11" style="font-size: 1px; line-height: 1px;"></td>
    </tr>

    <tr>
        <td>
            <table align="left">
                <tr>
                    <td style="font-size: 13px; font-family: Verdana, sans-serif; line-height: 18px; font-weight: 800; color: #606060">
                        New message
                    </td>
                </tr>
            </table>
        </td>
    </tr>

    <tr>
        <td height="10" style="font-size: 1px; line-height: 1px;"></td>
    </tr>

    <tr>
        <td height="28" style="font-size: 1px; line-height: 1px;"></td>
    </tr>

    <tr>
        <td style="font-size: 13px; font-family: Verdana, sans-serif; line-height: 18px; font-weight: 500 ; color: #606060;">
            Name : <?= $this->first_name . " " . $this->name ?></td>
    </tr>
    <tr>
        <td style="font-size: 13px; font-family: Verdana, sans-serif; line-height: 18px; font-weight: 500 ; color: #606060;">
            Email : <?= $this->email ?></td>
    </tr>
    <tr>
        <td style="font-size: 13px; font-family: Verdana, sans-serif; line-height: 18px; font-weight: 500 ; color: #606060;">
            Phone : <?= $this->phone_number ?? "N.A" ?></td>
    </tr>
    <tr>
        <td style="font-size: 13px; font-family: Verdana, sans-serif; line-height: 18px; font-weight: 500 ; color: #606060;">
            Company : <?= $this->company ?? "N.A" ?></td>
    </tr>
    <tr>
        <td height="28" style="font-size: 1px; line-height: 1px;"></td>
    </tr>
    <tr>
        <td style="font-size: 13px; font-family: Verdana, sans-serif; line-height: 18px; font-weight: 500 ; color: #606060;">
            Message :
        </td>
    </tr>

    <tr>
        <td style="font-size: 13px; font-family: Verdana, sans-serif; line-height: 18px; font-weight: 500 ; color: #606060;"> <?= $this->message ?></td>
    </tr>


    <tr>
        <td height="28" style="font-size: 1px; line-height: 1px;"></td>
    </tr>

    <tr>
        <td height="22" style="font-size: 1px; line-height: 1px;"></td>
    </tr>

    <tr>
        <td style="font-size: 13px; font-family: Verdana, sans-serif; line-height: 18px; font-weight: 800; color: #606060">
            Tradelist team
        </td>
    </tr>

    <tr>
        <td height="26" style="font-size: 1px; line-height: 1px;"></td>
    </tr>
    </tbody>
</table>